[package]
name = "sc-cli"
version = "0.55.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate CLI interface."
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
homepage = "https://paritytech.github.io/polkadot-sdk/"
repository = "https://github.com/paritytech/polkadot-sdk.git"
readme = "README.md"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
array-bytes = { version = "6.2.2", default-features = true }
bip39 = { package = "parity-bip39", version = "2.0.1", features = ["rand"] }
chrono = { version = "0.4.31" }
clap = { version = "4.5.13", features = ["derive", "string", "wrap_help"] }
codec = { package = "parity-scale-codec", version = "3.7.5", default-features = true }
fdlimit = { version = "0.3.0" }
futures = { version = "0.3.31" }
itertools = { version = "0.11" }
libp2p-identity = { version = "0.2.9", features = ["ed25519", "peerid"] }
log = { version = "0.4.22", default-features = true }
names = { version = "0.14.0", default-features = false }
rand = { version = "0.8.5", default-features = true }
regex = { version = "1.10.2" }
rpassword = { version = "7.0.0" }
sc-client-api = { version = "42.0.0", default-features = true }
sc-client-db = { version = "0.49.0", default-features = false }
sc-keystore = { version = "38.0.0", default-features = true }
sc-mixnet = { version = "0.23.0", default-features = true }
sc-network = { version = "0.53.0", default-features = true }
sc-service = { version = "0.54.0", default-features = false }
sc-telemetry = { version = "30.0.0", default-features = true }
sc-tracing = { version = "42.0.0", default-features = true }
sc-transaction-pool = { version = "42.0.0", default-features = true }
sc-utils = { version = "20.0.0", default-features = true }
serde = { version = "1.0.214", default-features = true }
serde_json = { version = "1.0.132", default-features = true }
sp-blockchain = { version = "42.0.0", default-features = true }
sp-core = { version = "38.1.0", default-features = true }
sp-keyring = { version = "44.0.0", default-features = true }
sp-keystore = { version = "0.44.1", default-features = true }
sp-panic-handler = { version = "13.0.2", default-features = true }
sp-runtime = { version = "44.0.0", default-features = true }
sp-version = { version = "42.0.0", default-features = true }
thiserror = { version = "1.0.64" }
tokio = { version = "1.45.0", features = ["parking_lot", "rt-multi-thread", "signal"], default-features = true }

[dev-dependencies]
futures-timer = { version = "3.0.2" }
sp-tracing = { version = "19.0.0", default-features = true }
tempfile = { version = "3.8.1" }

[features]
default = ["rocksdb"]
rocksdb = ["sc-client-db/rocksdb"]
